version: '3.7'

services:
  app:
    build:
      dockerfile: Dockerfile
    # image: task:v1
    ports:
      - 3000:3000
    # volumes:
    #   - ./app:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=mtsteta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    ports:
      - 5432:5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
