// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: api/proto/analytic.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnalyticClient is the client API for Analytic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticClient interface {
	ActionTask(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*AnalyticResponse, error)
}

type analyticClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticClient(cc grpc.ClientConnInterface) AnalyticClient {
	return &analyticClient{cc}
}

func (c *analyticClient) ActionTask(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*AnalyticResponse, error) {
	out := new(AnalyticResponse)
	err := c.cc.Invoke(ctx, "/api.Analytic/ActionTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticServer is the server API for Analytic service.
// All implementations must embed UnimplementedAnalyticServer
// for forward compatibility
type AnalyticServer interface {
	ActionTask(context.Context, *MessageRequest) (*AnalyticResponse, error)
	mustEmbedUnimplementedAnalyticServer()
}

// UnimplementedAnalyticServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticServer struct {
}

func (UnimplementedAnalyticServer) ActionTask(context.Context, *MessageRequest) (*AnalyticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActionTask not implemented")
}
func (UnimplementedAnalyticServer) mustEmbedUnimplementedAnalyticServer() {}

// UnsafeAnalyticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticServer will
// result in compilation errors.
type UnsafeAnalyticServer interface {
	mustEmbedUnimplementedAnalyticServer()
}

func RegisterAnalyticServer(s grpc.ServiceRegistrar, srv AnalyticServer) {
	s.RegisterService(&Analytic_ServiceDesc, srv)
}

func _Analytic_ActionTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServer).ActionTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Analytic/ActionTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServer).ActionTask(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Analytic_ServiceDesc is the grpc.ServiceDesc for Analytic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analytic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Analytic",
	HandlerType: (*AnalyticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActionTask",
			Handler:    _Analytic_ActionTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/analytic.proto",
}
